#!/usr/bin/env sh

set -eux

# Create environment variable file.
if test ! -f .env
then
  echo "  + Creating .env"
  cp .env.sample .env
else
  echo "  + Environment variable file (.env) found."
fi

# Install dependencies.
yarn install

# Initialize db for development.
yarn prisma migrate dev
yarn prisma migrate reset
